version: "2.4"

services:
  homeadguard:
    hostname: homeadguard
    container_name: homeadguard
    build:
      context: .
      dockerfile: Dockerfile
    mem_limit: 256m
    mem_reservation: 128m
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp" #DNS
      - "53:53/udp" #DNS
      - "80:80/tcp" # Web Interface
    volumes:
      - './data/work:/opt/adguardhome/work'
    dns:
      - 1.1.1.1
      - 208.67.222.222
      - 9.9.9.10
    logging:
        driver: "json-file"
        options:
            max-file: "10"
            max-size: "10m"
    restart: unless-stopped
